# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
absl-py
astunparse
attrs
audioread
backcall
beautifulsoup4
blas
bleach
bottleneck
ca-certificates
cachetools
certifi
cffi
chardet
colorama
cudatoolkit
cycler
decorator
defusedxml
entrypoints
fastai
fastprogress
freetype
future
gast
google-auth
google-auth-oauthlib
google-pasta
grpcio
h5py
icc_rt
icu
idna
importlib_metadata
intel-openmp
ipykernel
ipython
ipython_genutils
ipywidgets
jedi
jinja2
joblib
jpeg
jsonschema
jupyter
jupyter_client
jupyter_console
jupyter_core
keras
keras-applications
keras-preprocessing
kiwisolver
libpng
librosa
libsodium
libtiff
llvmlite
lz4-c
m2w64-gcc-libgfortran
m2w64-gcc-libs
m2w64-gcc-libs-core
m2w64-gmp
m2w64-libwinpthread-git
markdown
markupsafe
matplotlib
matplotlib-base
mistune
mkl
mkl-service
mkl_fft
mkl_random
msys2-conda-epoch
nbconvert
nbformat
netron
ninja
notebook
numba
numexpr
numpy
numpy-base
nvidia-ml-py3
oauthlib
olefile
openssl
opt-einsum
packaging
pandas
pandoc
pandocfilters
parso
pickleshare
pillow
pip
prometheus_client
prompt_toolkit
protobuf
pyasn1
pyasn1-modules
pycparser
pyfluidsynth
pygments
pyparsing
pyqt
pyrsistent
python
python-dateutil
pytorch
pytz
pywin32
pywinpty
pyyaml
pyzmq
qt
qtconsole
regex
requests
requests-oauthlib
resampy
rsa
scikit-learn
scipy
seaborn
send2trash
setuptools
sip
six
soundfile
soupsieve
sqlite
tensorboard
tensorboard-plugin-wit
tensorflow
tensorflow-estimator
termcolor
terminado
testpath
tk
torchvision
tornado
tqdm
traitlets
urllib3
vc
vs2015_runtime
wcwidth
webencodings
werkzeug
wheel
widgetsnbextension
wincertstore
winpty
wrapt
xz
zeromq
zipp
zlib
zstd
